title: "Justus Koch â€” Mechanical Engineering"
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Justus Koch"
github_username: "Justus-mb"
youtube_channel: ""
medium_username: ""
exclude:
  - "README.md"
